### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by MylesKingsnorth01** [grubersjoe/slide-menu#10]
I've installed the package via npm as per the documentation. I then include it in my gulp build script and run my compile command. The script fails with the following message, this only occurs when I include the `dist/slide-menu.js`.

```
events.js:173
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Users/myles/app/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at apply (/Users/myles/app/node_modules/gulp-uglify/node_modules/lodash/_apply.js:16:25)
    at wrapper (/Users/myles/app/node_modules/gulp-uglify/node_modules/lodash/_createCurry.js:41:12)
    at /Users/myles/app/node_modules/gulp-uglify/lib/minify.js:55:15
    at DestroyableTransform._transform (/Users/myles/app/node_modules/gulp-uglify/composer.js:12:19)
    at DestroyableTransform.Transform._read (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at DestroyableTransform.emit (events.js:197:13)
    at onwriteError (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:443:12)
    at onwrite (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:93:3)
    at DestroyableTransform._transform (/Users/myles/app/node_modules/gulp-uglify/composer.js:16:7)
    at DestroyableTransform.Transform._read (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/myles/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
```

Also on another note the version on npmjs.org is at 1.0.13 whereas this repo is at 1.0.12 which is very confusing. 

[https://www.npmjs.com/package/@grubersjoe/slide-menu/v/1.0.13](url)

**Comment by grubersjoe** [comment]
I've fixed the GitHub version, thanks for pointing this out.

About the Gulp error. Could you post your Gulp configuration, so this can be reproduced? For some reason the JS code can't be minified, but it's hard to tell what's wrong without further details.

**Comment by grubersjoe** [comment]
Closed due to inactivity.
